plugins {
	id 'com.android.application'
}

android {
	compileSdk 36
	
	defaultConfig {
		applicationId "com.zzok.medbook"
		namespace "com.zzok.medbook"
		minSdkVersion 21
		targetSdkVersion 36
		versionCode 53
		versionName "0.1.0-alpha.1"
	}
	
	buildTypes {
		release {
			minifyEnabled true
			shrinkResources true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}
	buildFeatures {
		viewBinding true
	}
}

dependencies {
	implementation 'androidx.appcompat:appcompat:1.7.1'
	implementation 'com.google.android.material:material:1.12.0'
	implementation 'androidx.core:core-splashscreen:1.0.1'
}
